An example where a subworkflow is called from a main workflow. When an error occurs in the subworkflow, 
the main workflow handles it in an exclosing try .. exception block.

![execution flow](subworkflow_error_handling.png?raw=true "subworkflow error handling")
